### ISSUE TITLE
refgenie manifest bismark container doesn't contain bowtie2-build

### ISSUE THREAD

**Issue by nsheff** [databio/hub.bulker.io#3]
bismark_genome_preparation doesn't work for me because the container doesn't contain bowtie2-build -- did you test this @michalstolarczyk ?

```
bismark_genome_preparation --bowtie2 /home/nsheff/sandbox/refgenie_bulker/hs38d1/bismark_bt2_index/default
Writing bisulfite genomes out into a single MFA (multi FastA) file

Bisulfite Genome Indexer version v0.17.0 (last modified 07 November 2016)

A directory called /home/nsheff/sandbox/refgenie_bulker/hs38d1/bismark_bt2_index/default/Bisulfite_Genome/ already exists. Bisulfite converted sequences and/or already existing Bowtie (1 or 2) indices will be overwritten!


Step I - Prepare genome folders - completed



Total number of conversions performed:
C->T:   1274343
G->A:   1235129
Please be aware that this process can - depending on genome size - take several hours!

Step II - Genome bisulfite conversions - completed


Bismark Genome Preparation - Step III: Launching the Bowtie 2 indexer
Can't exec "bowtie2-build": No such file or directory at /usr/local/bin/bismark_genome_preparation line 178, <IN> line 75966.
Parent process: Failed to build index
```

**Comment by stolarczyk** [comment]
Yeah, I tested all of them. It looks like I did not catch that it actually fails to build the asset.

I'll fix that

**Comment by nsheff** [comment]
How will you fix it?

The biocontainer for bismark doesn't contain bowtie2-build, but it calls this. So, if you're running bismark_genome_preparation in a container, it fails because the bowtie2-build command is not found (even if you have it locally; it has to be in the container as well).

I think that the problem is that the biocontainer is incomplete. So, I guess the only solution I can think of is to build a different container that also contains bowtie2 ? This is generic problem upstream in biocontainers, really.

**Comment by stolarczyk** [comment]
> So, I guess the only solution I can think of is to build a different container that also contains bowtie2 

this is what I wanted to do

I'll also let them know about the issue with the container
